name: Publish VSCode Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build extension
        run: npm run build
      
      - name: Package extension
        run: npm run package
      
      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## What's New in ${{ github.ref }}
            
            ### Features
            - Enhanced LLM prompt optimization
            - New command to show LLM prompts
            - Improved test generation quality
            - Better type safety and validation
            
            ### Bug Fixes
            - Fixed type inference issues
            - Improved error handling
            - Enhanced mock generation
            
            ### Technical Improvements
            - Optimized prompt structure for better LLM performance
            - Enhanced context extraction
            - Improved test validation
            
            ## Installation
            Install from the [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=ZezTechnology.zez-code-ai)
            
            ## Documentation
            - [Commands Guide](COMANDOS_EXTENSAO.md)
            - [LLM Test Completion](LLM_TEST_COMPLETION_FEATURE.md)
            - [Prompt Optimization Report](PROMPT_OPTIMIZATION_REPORT.md)
          draft: false
          prerelease: false 